

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class DODProjectStatusChartDataItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DODProjectStatusChartDataItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DODProjectStatusChartDataItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DODProjectStatusChartDataItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DODProjectStatusChartDataItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DODProjectStatusChartDataItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DODProjectStatusChartDataItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectStatus
        {
            get
            {
                return global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectStatus);
            }
            set
            {
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ProjectCount
        {
            get
            {
                return global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectCount);
            }
            set
            {
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectCount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectCount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectCount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectCount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Order
        {
            get
            {
                return global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Order);
            }
            set
            {
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Order, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DODProjectStatusChartDataItem,
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass,
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>.Entry
                __DODProjectStatusChartDataItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.__DODProjectStatusChartDataItem_CreateNew,
                    global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.__DODProjectStatusChartDataItem_Created,
                    global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.__DODProjectStatusChartDataItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DODProjectStatusChartDataItem __DODProjectStatusChartDataItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DODProjectStatusChartDataItem> es)
            {
                return new global::LightSwitchApplication.DODProjectStatusChartDataItem(es);
            }
            private static void __DODProjectStatusChartDataItem_Created(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
            {
                e.DODProjectStatusChartDataItem_Created();
            }
            private static bool __DODProjectStatusChartDataItem_AllowSaveWithErrors(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
            {
                bool result = false;
                e.DODProjectStatusChartDataItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string> ProjectStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal> ProjectCount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.ProjectCount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int> Order
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties.Order) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string ProjectStatus { get; set; }
                new decimal ProjectCount { get; set; }
                new int Order { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DODProjectStatusChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string>.Entry
                    ProjectStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string>.Entry(
                        "ProjectStatus",
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_Stub,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_Validate,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_GetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_SetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectStatus_OnValueChanged);
                private static void _ProjectStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectStatus, sf);
                }
                private static bool _ProjectStatus_ComputeIsReadOnly(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    bool result = false;
                    e.ProjectStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectStatus_Validate(global::LightSwitchApplication.DODProjectStatusChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectStatus_Validate(r);
                }
                private static string _ProjectStatus_GetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectStatus;
                }
                private static void _ProjectStatus_SetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectStatus = v;
                }
                private static void _ProjectStatus_OnValueChanged(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    e.ProjectStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal>.Entry
                    ProjectCount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal>.Entry(
                        "ProjectCount",
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_Stub,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_Validate,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_GetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_SetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._ProjectCount_OnValueChanged);
                private static void _ProjectCount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectCount, sf);
                }
                private static bool _ProjectCount_ComputeIsReadOnly(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    bool result = false;
                    e.ProjectCount_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectCount_Validate(global::LightSwitchApplication.DODProjectStatusChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectCount_Validate(r);
                }
                private static decimal _ProjectCount_GetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectCount;
                }
                private static void _ProjectCount_SetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.ProjectCount = v;
                }
                private static void _ProjectCount_OnValueChanged(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    e.ProjectCount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Entry
                    Order = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Entry(
                        "Order",
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_Stub,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_Validate,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_GetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_SetImplementationValue,
                        global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass.PropertySetProperties._Order_OnValueChanged);
                private static void _Order_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Order, sf);
                }
                private static bool _Order_ComputeIsReadOnly(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    bool result = false;
                    e.Order_IsReadOnly(ref result);
                    return result;
                }
                private static void _Order_Validate(global::LightSwitchApplication.DODProjectStatusChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Order_Validate(r);
                }
                private static int _Order_GetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Order;
                }
                private static void _Order_SetImplementationValue(global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Order = v;
                }
                private static void _Order_OnValueChanged(global::LightSwitchApplication.DODProjectStatusChartDataItem e)
                {
                    e.Order_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, string>.Data _ProjectStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, decimal>.Data _ProjectCount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODProjectStatusChartDataItem, global::LightSwitchApplication.DODProjectStatusChartDataItem.DetailsClass, int>.Data _Order;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class DODFeatureChartDataItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DODFeatureChartDataItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DODFeatureChartDataItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DODFeatureChartDataItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DODFeatureChartDataItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DODFeatureChartDataItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DODFeatureChartDataItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FeatureStatus
        {
            get
            {
                return global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureStatus);
            }
            set
            {
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int FeatureCount
        {
            get
            {
                return global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureCount);
            }
            set
            {
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureCount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureCount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureCount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FeatureCount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Order
        {
            get
            {
                return global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.GetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Order);
            }
            set
            {
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.SetValue(this, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Order, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Order_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DODFeatureChartDataItem,
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass,
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>.Entry
                __DODFeatureChartDataItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.__DODFeatureChartDataItem_CreateNew,
                    global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.__DODFeatureChartDataItem_Created,
                    global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.__DODFeatureChartDataItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DODFeatureChartDataItem __DODFeatureChartDataItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DODFeatureChartDataItem> es)
            {
                return new global::LightSwitchApplication.DODFeatureChartDataItem(es);
            }
            private static void __DODFeatureChartDataItem_Created(global::LightSwitchApplication.DODFeatureChartDataItem e)
            {
                e.DODFeatureChartDataItem_Created();
            }
            private static bool __DODFeatureChartDataItem_AllowSaveWithErrors(global::LightSwitchApplication.DODFeatureChartDataItem e)
            {
                bool result = false;
                e.DODFeatureChartDataItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string> FeatureStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int> FeatureCount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.FeatureCount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int> Order
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties.Order) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string FeatureStatus { get; set; }
                new int FeatureCount { get; set; }
                new int Order { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DODFeatureChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string>.Entry
                    FeatureStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string>.Entry(
                        "FeatureStatus",
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_Stub,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_Validate,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_GetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_SetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureStatus_OnValueChanged);
                private static void _FeatureStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FeatureStatus, sf);
                }
                private static bool _FeatureStatus_ComputeIsReadOnly(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    bool result = false;
                    e.FeatureStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _FeatureStatus_Validate(global::LightSwitchApplication.DODFeatureChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FeatureStatus_Validate(r);
                }
                private static string _FeatureStatus_GetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FeatureStatus;
                }
                private static void _FeatureStatus_SetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FeatureStatus = v;
                }
                private static void _FeatureStatus_OnValueChanged(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    e.FeatureStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry
                    FeatureCount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry(
                        "FeatureCount",
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_Stub,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_Validate,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_GetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_SetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._FeatureCount_OnValueChanged);
                private static void _FeatureCount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FeatureCount, sf);
                }
                private static bool _FeatureCount_ComputeIsReadOnly(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    bool result = false;
                    e.FeatureCount_IsReadOnly(ref result);
                    return result;
                }
                private static void _FeatureCount_Validate(global::LightSwitchApplication.DODFeatureChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FeatureCount_Validate(r);
                }
                private static int _FeatureCount_GetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FeatureCount;
                }
                private static void _FeatureCount_SetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.FeatureCount = v;
                }
                private static void _FeatureCount_OnValueChanged(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    e.FeatureCount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry
                    Order = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Entry(
                        "Order",
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_Stub,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_ComputeIsReadOnly,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_Validate,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_GetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_SetImplementationValue,
                        global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass.PropertySetProperties._Order_OnValueChanged);
                private static void _Order_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Order, sf);
                }
                private static bool _Order_ComputeIsReadOnly(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    bool result = false;
                    e.Order_IsReadOnly(ref result);
                    return result;
                }
                private static void _Order_Validate(global::LightSwitchApplication.DODFeatureChartDataItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Order_Validate(r);
                }
                private static int _Order_GetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Order;
                }
                private static void _Order_SetImplementationValue(global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Order = v;
                }
                private static void _Order_OnValueChanged(global::LightSwitchApplication.DODFeatureChartDataItem e)
                {
                    e.Order_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, string>.Data _FeatureStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data _FeatureCount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DODFeatureChartDataItem, global::LightSwitchApplication.DODFeatureChartDataItem.DetailsClass, int>.Data _Order;
            
        }
    
        #endregion
    }
    
    #endregion
}
