//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Provides the ability to mange projects
        /// </summary>
        public const string ProjectAdmin = "LightSwitchApplication:ProjectAdmin";
        /// <summary>
        /// Provides the ability to manage employees
        /// </summary>
        public const string EmployeeAdmin = "LightSwitchApplication:EmployeeAdmin";
        /// <summary>
        /// Provides the ability to manage employee assignments
        /// </summary>
        public const string EmpAssignAdmin = "LightSwitchApplication:EmpAssignAdmin";
        /// <summary>
        /// Provides the ability to manage staff requirements
        /// </summary>
        public const string StaffReqAdmin = "LightSwitchApplication:StaffReqAdmin";
        /// <summary>
        /// Provides the ability to manage time forecasts
        /// </summary>
        public const string TimeForecastUser = "LightSwitchApplication:TimeForecastUser";
        /// <summary>
        /// Can access management reports
        /// </summary>
        public const string MgmtReportAccess = "LightSwitchApplication:MgmtReportAccess";
        /// <summary>
        /// Can view and manage all projects
        /// </summary>
        public const string ProjectAdminAll = "LightSwitchApplication:ProjectAdminAll";
        /// <summary>
        /// Can edit all time forecasts and calendars
        /// </summary>
        public const string TimeForecastAdmin = "LightSwitchApplication:TimeForecastAdmin";
        /// <summary>
        /// Can access all reviews
        /// </summary>
        public const string ReviewAdmin = "LightSwitchApplication:ReviewAdmin";
        /// <summary>
        /// Can access all review setup information
        /// </summary>
        public const string ReviewSetupAdmin = "LightSwitchApplication:ReviewSetupAdmin";
        /// <summary>
        /// Can override and reset signatures
        /// </summary>
        public const string SignatureOverride = "LightSwitchApplication:SignatureOverride";
        /// <summary>
        /// Can create new reviews
        /// </summary>
        public const string CreateReviews = "LightSwitchApplication:CreateReviews";
        /// <summary>
        /// Can access any review info
        /// </summary>
        public const string AccessReviewTab = "LightSwitchApplication:AccessReviewTab";
        /// <summary>
        /// Can access features still in development
        /// </summary>
        public const string DevelopmentAdmin = "LightSwitchApplication:DevelopmentAdmin";
        /// <summary>
        /// Can access all Development On Demand sections to view and edit
        /// </summary>
        public const string DODSysAdmin = "LightSwitchApplication:DODSysAdmin";
        /// <summary>
        /// Provides the ability to use certain DOD sections
        /// </summary>
        public const string DODUser = "LightSwitchApplication:DODUser";
        /// <summary>
        /// Can access, review and edit all projects
        /// </summary>
        public const string DODManager = "LightSwitchApplication:DODManager";
        /// <summary>
        /// Can access, review and edit its own projects
        /// </summary>
        public const string DODDeveloper = "LightSwitchApplication:DODDeveloper";
        /// <summary>
        /// Can access information specific only to its own development
        /// </summary>
        public const string DODCustomer = "LightSwitchApplication:DODCustomer";
        /// <summary>
        /// Can access the Revenue Forecast Report
        /// </summary>
        public const string RevenueForecastUser = "LightSwitchApplication:RevenueForecastUser";
        /// <summary>
        /// Can export certain grids to Excel files in the Web application
        /// </summary>
        public const string ExportToExcel = "LightSwitchApplication:ExportToExcel";
        /// <summary>
        /// Can access the PTO Report
        /// </summary>
        public const string PTOReportUser = "LightSwitchApplication:PTOReportUser";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
