//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ApplicationData", "StaffingRequirement_Project", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Project), "StaffingRequirement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.StaffingRequirement), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "EmployeeAssignment_Project", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Project), "EmployeeAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.EmployeeAssignment), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "EmployeeAssignment_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Employee), "EmployeeAssignment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.EmployeeAssignment), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "Project_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ApplicationData.Implementation.Employee), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Project), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "Project_Employee1", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ApplicationData.Implementation.Employee), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Project), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "TimeForecast_Project", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Project), "TimeForecast", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.TimeForecast), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "TimeForecast_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Employee), "TimeForecast", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.TimeForecast), true)]

#endregion

namespace ApplicationData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StaffingRequirement> StaffingRequirements
        {
            get
            {
                if ((_StaffingRequirements == null))
                {
                    _StaffingRequirements = base.CreateObjectSet<StaffingRequirement>("StaffingRequirements");
                }
                return _StaffingRequirements;
            }
        }
        private ObjectSet<StaffingRequirement> _StaffingRequirements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmployeeAssignment> EmployeeAssignments
        {
            get
            {
                if ((_EmployeeAssignments == null))
                {
                    _EmployeeAssignments = base.CreateObjectSet<EmployeeAssignment>("EmployeeAssignments");
                }
                return _EmployeeAssignments;
            }
        }
        private ObjectSet<EmployeeAssignment> _EmployeeAssignments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TimeForecast> TimeForecasts
        {
            get
            {
                if ((_TimeForecasts == null))
                {
                    _TimeForecasts = base.CreateObjectSet<TimeForecast>("TimeForecasts");
                }
                return _TimeForecasts;
            }
        }
        private ObjectSet<TimeForecast> _TimeForecasts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ForecastException> ForecastExceptions
        {
            get
            {
                if ((_ForecastExceptions == null))
                {
                    _ForecastExceptions = base.CreateObjectSet<ForecastException>("ForecastExceptions");
                }
                return _ForecastExceptions;
            }
        }
        private ObjectSet<ForecastException> _ForecastExceptions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StaffingRequirements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStaffingRequirements(StaffingRequirement staffingRequirement)
        {
            base.AddObject("StaffingRequirements", staffingRequirement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmployeeAssignments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployeeAssignments(EmployeeAssignment employeeAssignment)
        {
            base.AddObject("EmployeeAssignments", employeeAssignment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TimeForecasts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimeForecasts(TimeForecast timeForecast)
        {
            base.AddObject("TimeForecasts", timeForecast);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ForecastExceptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForecastExceptions(ForecastException forecastException)
        {
            base.AddObject("ForecastExceptions", forecastException);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.String userID, global::System.String firstName, global::System.String lastName, global::System.String title)
        {
            Employee employee = new Employee();
            employee.Id = id;
            employee.UserID = userID;
            employee.FirstName = firstName;
            employee.LastName = lastName;
            employee.Title = title;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "EmployeeAssignment_Employee", "EmployeeAssignment")]
        public EntityCollection<EmployeeAssignment> EmployeeAssignments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmployeeAssignment>("ApplicationData.EmployeeAssignment_Employee", "EmployeeAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmployeeAssignment>("ApplicationData.EmployeeAssignment_Employee", "EmployeeAssignment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Project_Employee", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("ApplicationData.Project_Employee", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("ApplicationData.Project_Employee", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Project_Employee1", "Project")]
        public EntityCollection<Project> Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("ApplicationData.Project_Employee1", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("ApplicationData.Project_Employee1", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "TimeForecast_Employee", "TimeForecast")]
        public EntityCollection<TimeForecast> TimeForecasts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TimeForecast>("ApplicationData.TimeForecast_Employee", "TimeForecast");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TimeForecast>("ApplicationData.TimeForecast_Employee", "TimeForecast", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="EmployeeAssignment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmployeeAssignment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmployeeAssignment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="percent">Initial value of the Percent property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="employeeAssignment_Project">Initial value of the EmployeeAssignment_Project property.</param>
        /// <param name="employeeAssignment_Employee">Initial value of the EmployeeAssignment_Employee property.</param>
        public static EmployeeAssignment CreateEmployeeAssignment(global::System.Int32 id, global::System.Decimal percent, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Int32 employeeAssignment_Project, global::System.Int32 employeeAssignment_Employee)
        {
            EmployeeAssignment employeeAssignment = new EmployeeAssignment();
            employeeAssignment.Id = id;
            employeeAssignment.Percent = percent;
            employeeAssignment.StartDate = startDate;
            employeeAssignment.EndDate = endDate;
            employeeAssignment.EmployeeAssignment_Project = employeeAssignment_Project;
            employeeAssignment.EmployeeAssignment_Employee = employeeAssignment_Employee;
            return employeeAssignment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Percent
        {
            get
            {
                return _Percent;
            }
            set
            {
                OnPercentChanging(value);
                ReportPropertyChanging("Percent");
                _Percent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percent");
                OnPercentChanged();
            }
        }
        private global::System.Decimal _Percent;
        partial void OnPercentChanging(global::System.Decimal value);
        partial void OnPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeAssignment_Project
        {
            get
            {
                return _EmployeeAssignment_Project;
            }
            set
            {
                OnEmployeeAssignment_ProjectChanging(value);
                ReportPropertyChanging("EmployeeAssignment_Project");
                _EmployeeAssignment_Project = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeAssignment_Project");
                OnEmployeeAssignment_ProjectChanged();
            }
        }
        private global::System.Int32 _EmployeeAssignment_Project;
        partial void OnEmployeeAssignment_ProjectChanging(global::System.Int32 value);
        partial void OnEmployeeAssignment_ProjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeAssignment_Employee
        {
            get
            {
                return _EmployeeAssignment_Employee;
            }
            set
            {
                OnEmployeeAssignment_EmployeeChanging(value);
                ReportPropertyChanging("EmployeeAssignment_Employee");
                _EmployeeAssignment_Employee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeAssignment_Employee");
                OnEmployeeAssignment_EmployeeChanged();
            }
        }
        private global::System.Int32 _EmployeeAssignment_Employee;
        partial void OnEmployeeAssignment_EmployeeChanging(global::System.Int32 value);
        partial void OnEmployeeAssignment_EmployeeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "EmployeeAssignment_Project", "Project")]
        public Project Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.EmployeeAssignment_Project", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.EmployeeAssignment_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.EmployeeAssignment_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("ApplicationData.EmployeeAssignment_Project", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "EmployeeAssignment_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.EmployeeAssignment_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.EmployeeAssignment_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.EmployeeAssignment_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("ApplicationData.EmployeeAssignment_Employee", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="ForecastException")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ForecastException : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ForecastException object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="exception">Initial value of the Exception property.</param>
        public static ForecastException CreateForecastException(global::System.Int32 id, global::System.String exception)
        {
            ForecastException forecastException = new ForecastException();
            forecastException.Id = id;
            forecastException.Exception = exception;
            return forecastException;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="projectName">Initial value of the ProjectName property.</param>
        /// <param name="client">Initial value of the Client property.</param>
        /// <param name="phase">Initial value of the Phase property.</param>
        /// <param name="projectStatus">Initial value of the ProjectStatus property.</param>
        /// <param name="staffingStatus">Initial value of the StaffingStatus property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="projectedEndDate">Initial value of the ProjectedEndDate property.</param>
        /// <param name="closed">Initial value of the Closed property.</param>
        /// <param name="chargeable">Initial value of the Chargeable property.</param>
        public static Project CreateProject(global::System.Int32 id, global::System.String projectName, global::System.String client, global::System.String phase, global::System.Double projectStatus, global::System.Double staffingStatus, global::System.DateTime startDate, global::System.DateTime projectedEndDate, global::System.Boolean closed, global::System.Boolean chargeable)
        {
            Project project = new Project();
            project.Id = id;
            project.ProjectName = projectName;
            project.Client = client;
            project.Phase = phase;
            project.ProjectStatus = projectStatus;
            project.StaffingStatus = staffingStatus;
            project.StartDate = startDate;
            project.ProjectedEndDate = projectedEndDate;
            project.Closed = closed;
            project.Chargeable = chargeable;
            return project;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Client
        {
            get
            {
                return _Client;
            }
            set
            {
                OnClientChanging(value);
                ReportPropertyChanging("Client");
                _Client = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Client");
                OnClientChanged();
            }
        }
        private global::System.String _Client;
        partial void OnClientChanging(global::System.String value);
        partial void OnClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phase
        {
            get
            {
                return _Phase;
            }
            set
            {
                OnPhaseChanging(value);
                ReportPropertyChanging("Phase");
                _Phase = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phase");
                OnPhaseChanged();
            }
        }
        private global::System.String _Phase;
        partial void OnPhaseChanging(global::System.String value);
        partial void OnPhaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ProjectStatus
        {
            get
            {
                return _ProjectStatus;
            }
            set
            {
                OnProjectStatusChanging(value);
                ReportPropertyChanging("ProjectStatus");
                _ProjectStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectStatus");
                OnProjectStatusChanged();
            }
        }
        private global::System.Double _ProjectStatus;
        partial void OnProjectStatusChanging(global::System.Double value);
        partial void OnProjectStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double StaffingStatus
        {
            get
            {
                return _StaffingStatus;
            }
            set
            {
                OnStaffingStatusChanging(value);
                ReportPropertyChanging("StaffingStatus");
                _StaffingStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaffingStatus");
                OnStaffingStatusChanged();
            }
        }
        private global::System.Double _StaffingStatus;
        partial void OnStaffingStatusChanging(global::System.Double value);
        partial void OnStaffingStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FollowOn
        {
            get
            {
                return _FollowOn;
            }
            set
            {
                OnFollowOnChanging(value);
                ReportPropertyChanging("FollowOn");
                _FollowOn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FollowOn");
                OnFollowOnChanged();
            }
        }
        private global::System.String _FollowOn;
        partial void OnFollowOnChanging(global::System.String value);
        partial void OnFollowOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ProjectedEndDate
        {
            get
            {
                return _ProjectedEndDate;
            }
            set
            {
                OnProjectedEndDateChanging(value);
                ReportPropertyChanging("ProjectedEndDate");
                _ProjectedEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectedEndDate");
                OnProjectedEndDateChanged();
            }
        }
        private global::System.DateTime _ProjectedEndDate;
        partial void OnProjectedEndDateChanging(global::System.DateTime value);
        partial void OnProjectedEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Closed
        {
            get
            {
                return _Closed;
            }
            set
            {
                OnClosedChanging(value);
                ReportPropertyChanging("Closed");
                _Closed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Closed");
                OnClosedChanged();
            }
        }
        private global::System.Boolean _Closed;
        partial void OnClosedChanging(global::System.Boolean value);
        partial void OnClosedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Chargeable
        {
            get
            {
                return _Chargeable;
            }
            set
            {
                OnChargeableChanging(value);
                ReportPropertyChanging("Chargeable");
                _Chargeable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chargeable");
                OnChargeableChanged();
            }
        }
        private global::System.Boolean _Chargeable;
        partial void OnChargeableChanging(global::System.Boolean value);
        partial void OnChargeableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Project_Employee
        {
            get
            {
                return _Project_Employee;
            }
            set
            {
                OnProject_EmployeeChanging(value);
                ReportPropertyChanging("Project_Employee");
                _Project_Employee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Project_Employee");
                OnProject_EmployeeChanged();
            }
        }
        private Nullable<global::System.Int32> _Project_Employee;
        partial void OnProject_EmployeeChanging(Nullable<global::System.Int32> value);
        partial void OnProject_EmployeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Project_Employee1
        {
            get
            {
                return _Project_Employee1;
            }
            set
            {
                OnProject_Employee1Changing(value);
                ReportPropertyChanging("Project_Employee1");
                _Project_Employee1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Project_Employee1");
                OnProject_Employee1Changed();
            }
        }
        private Nullable<global::System.Int32> _Project_Employee1;
        partial void OnProject_Employee1Changing(Nullable<global::System.Int32> value);
        partial void OnProject_Employee1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "StaffingRequirement_Project", "StaffingRequirement")]
        public EntityCollection<StaffingRequirement> StaffingRequirements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StaffingRequirement>("ApplicationData.StaffingRequirement_Project", "StaffingRequirement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StaffingRequirement>("ApplicationData.StaffingRequirement_Project", "StaffingRequirement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "EmployeeAssignment_Project", "EmployeeAssignment")]
        public EntityCollection<EmployeeAssignment> EmployeeAssignment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmployeeAssignment>("ApplicationData.EmployeeAssignment_Project", "EmployeeAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmployeeAssignment>("ApplicationData.EmployeeAssignment_Project", "EmployeeAssignment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Project_Employee", "Employee")]
        public Employee Director
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> DirectorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("ApplicationData.Project_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Project_Employee1", "Employee")]
        public Employee Manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee1", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee1", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> ManagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.Project_Employee1", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("ApplicationData.Project_Employee1", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "TimeForecast_Project", "TimeForecast")]
        public EntityCollection<TimeForecast> TimeForecasts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TimeForecast>("ApplicationData.TimeForecast_Project", "TimeForecast");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TimeForecast>("ApplicationData.TimeForecast_Project", "TimeForecast", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="StaffingRequirement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StaffingRequirement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StaffingRequirement object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="level">Initial value of the Level property.</param>
        /// <param name="skill">Initial value of the Skill property.</param>
        /// <param name="industry">Initial value of the Industry property.</param>
        /// <param name="fTEs">Initial value of the FTEs property.</param>
        /// <param name="dateRequired">Initial value of the DateRequired property.</param>
        /// <param name="staffingRequirement_Project">Initial value of the StaffingRequirement_Project property.</param>
        public static StaffingRequirement CreateStaffingRequirement(global::System.Int32 id, global::System.Int16 level, global::System.Int16 skill, global::System.Int16 industry, global::System.Decimal fTEs, global::System.DateTime dateRequired, global::System.Int32 staffingRequirement_Project)
        {
            StaffingRequirement staffingRequirement = new StaffingRequirement();
            staffingRequirement.Id = id;
            staffingRequirement.Level = level;
            staffingRequirement.Skill = skill;
            staffingRequirement.Industry = industry;
            staffingRequirement.FTEs = fTEs;
            staffingRequirement.DateRequired = dateRequired;
            staffingRequirement.StaffingRequirement_Project = staffingRequirement_Project;
            return staffingRequirement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private global::System.Int16 _Level;
        partial void OnLevelChanging(global::System.Int16 value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Skill
        {
            get
            {
                return _Skill;
            }
            set
            {
                OnSkillChanging(value);
                ReportPropertyChanging("Skill");
                _Skill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Skill");
                OnSkillChanged();
            }
        }
        private global::System.Int16 _Skill;
        partial void OnSkillChanging(global::System.Int16 value);
        partial void OnSkillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Industry
        {
            get
            {
                return _Industry;
            }
            set
            {
                OnIndustryChanging(value);
                ReportPropertyChanging("Industry");
                _Industry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Industry");
                OnIndustryChanged();
            }
        }
        private global::System.Int16 _Industry;
        partial void OnIndustryChanging(global::System.Int16 value);
        partial void OnIndustryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FTEs
        {
            get
            {
                return _FTEs;
            }
            set
            {
                OnFTEsChanging(value);
                ReportPropertyChanging("FTEs");
                _FTEs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FTEs");
                OnFTEsChanged();
            }
        }
        private global::System.Decimal _FTEs;
        partial void OnFTEsChanging(global::System.Decimal value);
        partial void OnFTEsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateRequired
        {
            get
            {
                return _DateRequired;
            }
            set
            {
                OnDateRequiredChanging(value);
                ReportPropertyChanging("DateRequired");
                _DateRequired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateRequired");
                OnDateRequiredChanged();
            }
        }
        private global::System.DateTime _DateRequired;
        partial void OnDateRequiredChanging(global::System.DateTime value);
        partial void OnDateRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StaffingRequirement_Project
        {
            get
            {
                return _StaffingRequirement_Project;
            }
            set
            {
                OnStaffingRequirement_ProjectChanging(value);
                ReportPropertyChanging("StaffingRequirement_Project");
                _StaffingRequirement_Project = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaffingRequirement_Project");
                OnStaffingRequirement_ProjectChanged();
            }
        }
        private global::System.Int32 _StaffingRequirement_Project;
        partial void OnStaffingRequirement_ProjectChanging(global::System.Int32 value);
        partial void OnStaffingRequirement_ProjectChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "StaffingRequirement_Project", "Project")]
        public Project Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.StaffingRequirement_Project", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.StaffingRequirement_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.StaffingRequirement_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("ApplicationData.StaffingRequirement_Project", "Project", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="TimeForecast")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TimeForecast : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TimeForecast object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="percent">Initial value of the Percent property.</param>
        /// <param name="chargeable">Initial value of the Chargeable property.</param>
        /// <param name="lastUpdate">Initial value of the LastUpdate property.</param>
        /// <param name="timeForecast_Project">Initial value of the TimeForecast_Project property.</param>
        /// <param name="timeForecast_Employee">Initial value of the TimeForecast_Employee property.</param>
        public static TimeForecast CreateTimeForecast(global::System.Int32 id, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Int32 percent, global::System.Boolean chargeable, global::System.DateTime lastUpdate, global::System.Int32 timeForecast_Project, global::System.Int32 timeForecast_Employee)
        {
            TimeForecast timeForecast = new TimeForecast();
            timeForecast.Id = id;
            timeForecast.StartDate = startDate;
            timeForecast.EndDate = endDate;
            timeForecast.Percent = percent;
            timeForecast.Chargeable = chargeable;
            timeForecast.LastUpdate = lastUpdate;
            timeForecast.TimeForecast_Project = timeForecast_Project;
            timeForecast.TimeForecast_Employee = timeForecast_Employee;
            return timeForecast;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Percent
        {
            get
            {
                return _Percent;
            }
            set
            {
                OnPercentChanging(value);
                ReportPropertyChanging("Percent");
                _Percent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percent");
                OnPercentChanged();
            }
        }
        private global::System.Int32 _Percent;
        partial void OnPercentChanging(global::System.Int32 value);
        partial void OnPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Chargeable
        {
            get
            {
                return _Chargeable;
            }
            set
            {
                OnChargeableChanging(value);
                ReportPropertyChanging("Chargeable");
                _Chargeable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chargeable");
                OnChargeableChanged();
            }
        }
        private global::System.Boolean _Chargeable;
        partial void OnChargeableChanging(global::System.Boolean value);
        partial void OnChargeableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private global::System.DateTime _LastUpdate;
        partial void OnLastUpdateChanging(global::System.DateTime value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeForecast_Project
        {
            get
            {
                return _TimeForecast_Project;
            }
            set
            {
                OnTimeForecast_ProjectChanging(value);
                ReportPropertyChanging("TimeForecast_Project");
                _TimeForecast_Project = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeForecast_Project");
                OnTimeForecast_ProjectChanged();
            }
        }
        private global::System.Int32 _TimeForecast_Project;
        partial void OnTimeForecast_ProjectChanging(global::System.Int32 value);
        partial void OnTimeForecast_ProjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeForecast_Employee
        {
            get
            {
                return _TimeForecast_Employee;
            }
            set
            {
                OnTimeForecast_EmployeeChanging(value);
                ReportPropertyChanging("TimeForecast_Employee");
                _TimeForecast_Employee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeForecast_Employee");
                OnTimeForecast_EmployeeChanged();
            }
        }
        private global::System.Int32 _TimeForecast_Employee;
        partial void OnTimeForecast_EmployeeChanging(global::System.Int32 value);
        partial void OnTimeForecast_EmployeeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "TimeForecast_Project", "Project")]
        public Project Project1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.TimeForecast_Project", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.TimeForecast_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> Project1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("ApplicationData.TimeForecast_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("ApplicationData.TimeForecast_Project", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "TimeForecast_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.TimeForecast_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.TimeForecast_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("ApplicationData.TimeForecast_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("ApplicationData.TimeForecast_Employee", "Employee", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
